name: Generate Database Index

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-index:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Generate database index
      run: npm run build

    - name: Commit version.json file
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "ci: auto-generate version.json"
        # ======================================================
        # هذا هو التعديل الوحيد والمهم
        # أخبرنا الأداة أن تحفظ هذا الملف فقط
        file_pattern: docs/version.json
        # ======================================================
