name: Generate Database Index

on:
  push:
    branches:
      - main

jobs:
  generate-index:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Generate database index
        run: node generateIndex.js
        
      - name: Commit generated database.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update database.json [skip ci]"
          file_pattern: "site/database.json"
